CREATE TABLE IF NOT EXISTS MPA_RATING (
    rating_id INT PRIMARY KEY AUTO_INCREMENT,
    rating_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS DIRECTORS (
    director_id INT PRIMARY KEY AUTO_INCREMENT,
    director_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM (
    film_id INT PRIMARY KEY AUTO_INCREMENT,
    film_name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    release_date DATE,
    duration INT,
    rating_MPA INT REFERENCES MPA_RATING (rating_id),
    director_id INT REFERENCES DIRECTORS (director_id)
);
